import { writeFile } from "fs/promises";
import { CONFIG, thinkPath } from "./config";
import { parseMarkdown } from "./parser";

/**
 * Generate CLAUDE.md from ~/.think sources
 * Outputs to ~/.claude/CLAUDE.md which Claude reads automatically
 */
export async function generatePlugin(): Promise<void> {
  // Read all files in parallel
  const [profile, tools, patterns, antiPatterns, learnings, corrections, subagents, workflows] =
    await Promise.all([
      parseMarkdown(thinkPath(CONFIG.files.profile)),
      parseMarkdown(thinkPath(CONFIG.files.tools)),
      parseMarkdown(thinkPath(CONFIG.files.patterns)),
      parseMarkdown(thinkPath(CONFIG.files.antiPatterns)),
      parseMarkdown(thinkPath(CONFIG.files.learnings)),
      parseMarkdown(thinkPath(CONFIG.files.corrections)),
      parseMarkdown(thinkPath(CONFIG.files.subagents)),
      parseMarkdown(thinkPath(CONFIG.files.workflows)),
    ]);

  const sections: string[] = [];

  sections.push("# Personal Context\n");
  sections.push("This context is auto-generated by `think sync`. Edit files in ~/.think instead.\n");

  // Profile
  if (profile) {
    sections.push("## About the User\n");
    if (profile.frontmatter?.name) {
      sections.push(`Name: ${profile.frontmatter.name}\n`);
    }
    if (profile.content) {
      sections.push(profile.content);
    }
    sections.push("");
  }

  // Tool preferences
  if (tools?.content) {
    sections.push("## Tool Preferences\n");
    sections.push(tools.content);
    sections.push("");
  }

  // Patterns
  if (patterns?.content) {
    sections.push("## Patterns to Follow\n");
    sections.push(patterns.content);
    sections.push("");
  }

  // Anti-patterns
  if (antiPatterns?.content) {
    sections.push("## Anti-Patterns to Avoid\n");
    sections.push(antiPatterns.content);
    sections.push("");
  }

  // Learnings
  if (learnings?.content) {
    sections.push("## Memory - Learnings\n");
    sections.push(learnings.content);
    sections.push("");
  }

  // Corrections
  if (corrections?.content) {
    sections.push("## Memory - Corrections\n");
    sections.push(corrections.content);
    sections.push("");
  }

  // Subagent automation
  if (subagents?.content) {
    sections.push("## Automation - Subagents\n");
    sections.push("Follow these rules for automatically spawning subagents:\n");
    sections.push(subagents.content);
    sections.push("");
  }

  // Workflows
  if (workflows?.content) {
    sections.push("## Automation - Workflows\n");
    sections.push(workflows.content);
    sections.push("");
  }

  await writeFile(CONFIG.claudeMdPath, sections.join("\n"));
}
